routes:
  /:
    template: index
  /podcast/:
    template: page-podcast
    data: page.podcast

collections:
  /podcast/:
    permalink: /podcast/{slug}/
    template: podcast
    filter: primary_tag:podcast
  /:
    permalink: /{slug}/
    template: paged
    filter: primary_tag:-podcast

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
